---

- name: Required Packages
  package:
    pkg: "{{ item }}"
    state: present
  with_items:
    - php
    - httpd

- name: Required Packages (RHEL)
  package:
    pkg: "{{ item }}"
    state: present
  with_items:
    - php-json
    - mariadb
    - mariadb-server
    - php-mysqlnd
#    - python2-PyMySQL
#    - mariadb-devel
#    - gcc
#    - gcc-c++
#    - python3-devel
#    - redhat-rpm-config
  when:
    (ansible_distribution == 'RedHat') or
    (ansible_distribution == 'Fedora') or
    (ansible_distribution == 'CentOS')


- name: Start and enable mysql
  service:
    name: mariadb
    state: started
    enabled: true
