# tasks file for wordpress
---
- include: dependencies.yml

- include: wp-cli.yml
  tags:
    - configuration
    - wordpress
    - wordpress-wp-cli

- include: database.yml
  tags:
    - configuration
    - wordpress
    - wordpress-core

- include: core.yml
  tags:
    - configuration
    - wordpress
    - wordpress-core

- include: configure.yml
  tags:
    - configuration
    - wordpress
    - wordpress-configure

- include: wp-cron.yml
  tags:
    - configuration
    - wordpress
    - wordpress-wp-cron

- include: themes.yml
  tags:
    - configuration
    - wordpress
    - wordpress-themes

- include: plugins.yml
  tags:
    - configuration
    - wordpress
    - wordpress-plugins

- include: users.yml
  tags:
    - configuration
    - wordpress
    - wordpress-users

- include: options.yml
  tags:
    - configuration
    - wordpress
    - wordpress-options

- include: queries.yml
  tags:
    - configuration
    - wordpress
    - wordpress-queries

- include: chown.yml
  tags:
    - configuration
    - wordpress
    - wordpress-chown

- name: Restart httpd
  service:
    name: httpd
    state: restart
  when:
    (ansible_distribution == 'RedHat') or
    (ansible_distribution == 'Fedora') or
    (ansible_distribution == 'CentOS')
