# tasks file for wordpress, wp-cli
---
- name: wp-cli | install
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: "{{ wordpress_wp_cli_install_dir }}/wp-cli"
    force: true
    owner: root
    group: root
    mode: 0755
  tags:
    - wordpress-wp-cli-install
